// Generated by gencpp from file service_demo/Greeting.msg
// DO NOT EDIT!


#ifndef SERVICE_DEMO_MESSAGE_GREETING_H
#define SERVICE_DEMO_MESSAGE_GREETING_H

#include <ros/service_traits.h>


#include <service_demo/GreetingRequest.h>
#include <service_demo/GreetingResponse.h>


namespace service_demo
{

struct Greeting
{

typedef GreetingRequest Request;
typedef GreetingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Greeting
} // namespace service_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_demo::Greeting > {
  static const char* value()
  {
    return "116e2074a4605229af423317e5dff099";
  }

  static const char* value(const ::service_demo::Greeting&) { return value(); }
};

template<>
struct DataType< ::service_demo::Greeting > {
  static const char* value()
  {
    return "service_demo/Greeting";
  }

  static const char* value(const ::service_demo::Greeting&) { return value(); }
};


// service_traits::MD5Sum< ::service_demo::GreetingRequest> should match 
// service_traits::MD5Sum< ::service_demo::Greeting > 
template<>
struct MD5Sum< ::service_demo::GreetingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_demo::Greeting >::value();
  }
  static const char* value(const ::service_demo::GreetingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_demo::GreetingRequest> should match 
// service_traits::DataType< ::service_demo::Greeting > 
template<>
struct DataType< ::service_demo::GreetingRequest>
{
  static const char* value()
  {
    return DataType< ::service_demo::Greeting >::value();
  }
  static const char* value(const ::service_demo::GreetingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_demo::GreetingResponse> should match 
// service_traits::MD5Sum< ::service_demo::Greeting > 
template<>
struct MD5Sum< ::service_demo::GreetingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_demo::Greeting >::value();
  }
  static const char* value(const ::service_demo::GreetingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_demo::GreetingResponse> should match 
// service_traits::DataType< ::service_demo::Greeting > 
template<>
struct DataType< ::service_demo::GreetingResponse>
{
  static const char* value()
  {
    return DataType< ::service_demo::Greeting >::value();
  }
  static const char* value(const ::service_demo::GreetingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_DEMO_MESSAGE_GREETING_H
