// Generated by gencpp from file msgs_demo/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MSGS_DEMO_MESSAGE_ADDTWOINTS_H
#define MSGS_DEMO_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <msgs_demo/AddTwoIntsRequest.h>
#include <msgs_demo/AddTwoIntsResponse.h>


namespace msgs_demo
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace msgs_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msgs_demo::AddTwoInts > {
  static const char* value()
  {
    return "f0b6d69ea10b0cf210cb349d58d59e8f";
  }

  static const char* value(const ::msgs_demo::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::msgs_demo::AddTwoInts > {
  static const char* value()
  {
    return "msgs_demo/AddTwoInts";
  }

  static const char* value(const ::msgs_demo::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::msgs_demo::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::msgs_demo::AddTwoInts > 
template<>
struct MD5Sum< ::msgs_demo::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::AddTwoInts >::value();
  }
  static const char* value(const ::msgs_demo::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::AddTwoIntsRequest> should match 
// service_traits::DataType< ::msgs_demo::AddTwoInts > 
template<>
struct DataType< ::msgs_demo::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::AddTwoInts >::value();
  }
  static const char* value(const ::msgs_demo::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msgs_demo::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::msgs_demo::AddTwoInts > 
template<>
struct MD5Sum< ::msgs_demo::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::AddTwoInts >::value();
  }
  static const char* value(const ::msgs_demo::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::AddTwoIntsResponse> should match 
// service_traits::DataType< ::msgs_demo::AddTwoInts > 
template<>
struct DataType< ::msgs_demo::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::AddTwoInts >::value();
  }
  static const char* value(const ::msgs_demo::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSGS_DEMO_MESSAGE_ADDTWOINTS_H
