// Generated by gencpp from file msgs_demo/GetPlan.msg
// DO NOT EDIT!


#ifndef MSGS_DEMO_MESSAGE_GETPLAN_H
#define MSGS_DEMO_MESSAGE_GETPLAN_H

#include <ros/service_traits.h>


#include <msgs_demo/GetPlanRequest.h>
#include <msgs_demo/GetPlanResponse.h>


namespace msgs_demo
{

struct GetPlan
{

typedef GetPlanRequest Request;
typedef GetPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlan
} // namespace msgs_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msgs_demo::GetPlan > {
  static const char* value()
  {
    return "421c8ea4d21c6c9db7054b4bbdf1e024";
  }

  static const char* value(const ::msgs_demo::GetPlan&) { return value(); }
};

template<>
struct DataType< ::msgs_demo::GetPlan > {
  static const char* value()
  {
    return "msgs_demo/GetPlan";
  }

  static const char* value(const ::msgs_demo::GetPlan&) { return value(); }
};


// service_traits::MD5Sum< ::msgs_demo::GetPlanRequest> should match 
// service_traits::MD5Sum< ::msgs_demo::GetPlan > 
template<>
struct MD5Sum< ::msgs_demo::GetPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::GetPlan >::value();
  }
  static const char* value(const ::msgs_demo::GetPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::GetPlanRequest> should match 
// service_traits::DataType< ::msgs_demo::GetPlan > 
template<>
struct DataType< ::msgs_demo::GetPlanRequest>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::GetPlan >::value();
  }
  static const char* value(const ::msgs_demo::GetPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msgs_demo::GetPlanResponse> should match 
// service_traits::MD5Sum< ::msgs_demo::GetPlan > 
template<>
struct MD5Sum< ::msgs_demo::GetPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::GetPlan >::value();
  }
  static const char* value(const ::msgs_demo::GetPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::GetPlanResponse> should match 
// service_traits::DataType< ::msgs_demo::GetPlan > 
template<>
struct DataType< ::msgs_demo::GetPlanResponse>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::GetPlan >::value();
  }
  static const char* value(const ::msgs_demo::GetPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSGS_DEMO_MESSAGE_GETPLAN_H
