// Generated by gencpp from file msgs_demo/SetBool.msg
// DO NOT EDIT!


#ifndef MSGS_DEMO_MESSAGE_SETBOOL_H
#define MSGS_DEMO_MESSAGE_SETBOOL_H

#include <ros/service_traits.h>


#include <msgs_demo/SetBoolRequest.h>
#include <msgs_demo/SetBoolResponse.h>


namespace msgs_demo
{

struct SetBool
{

typedef SetBoolRequest Request;
typedef SetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBool
} // namespace msgs_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msgs_demo::SetBool > {
  static const char* value()
  {
    return "09fb03525b03e7ea1fd3992bafd87e16";
  }

  static const char* value(const ::msgs_demo::SetBool&) { return value(); }
};

template<>
struct DataType< ::msgs_demo::SetBool > {
  static const char* value()
  {
    return "msgs_demo/SetBool";
  }

  static const char* value(const ::msgs_demo::SetBool&) { return value(); }
};


// service_traits::MD5Sum< ::msgs_demo::SetBoolRequest> should match 
// service_traits::MD5Sum< ::msgs_demo::SetBool > 
template<>
struct MD5Sum< ::msgs_demo::SetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::SetBool >::value();
  }
  static const char* value(const ::msgs_demo::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::SetBoolRequest> should match 
// service_traits::DataType< ::msgs_demo::SetBool > 
template<>
struct DataType< ::msgs_demo::SetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::SetBool >::value();
  }
  static const char* value(const ::msgs_demo::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msgs_demo::SetBoolResponse> should match 
// service_traits::MD5Sum< ::msgs_demo::SetBool > 
template<>
struct MD5Sum< ::msgs_demo::SetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::SetBool >::value();
  }
  static const char* value(const ::msgs_demo::SetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::SetBoolResponse> should match 
// service_traits::DataType< ::msgs_demo::SetBool > 
template<>
struct DataType< ::msgs_demo::SetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::SetBool >::value();
  }
  static const char* value(const ::msgs_demo::SetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSGS_DEMO_MESSAGE_SETBOOL_H
