// Generated by gencpp from file msgs_demo/SetMap.msg
// DO NOT EDIT!


#ifndef MSGS_DEMO_MESSAGE_SETMAP_H
#define MSGS_DEMO_MESSAGE_SETMAP_H

#include <ros/service_traits.h>


#include <msgs_demo/SetMapRequest.h>
#include <msgs_demo/SetMapResponse.h>


namespace msgs_demo
{

struct SetMap
{

typedef SetMapRequest Request;
typedef SetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMap
} // namespace msgs_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msgs_demo::SetMap > {
  static const char* value()
  {
    return "c36922319011e63ed7784112ad4fdd32";
  }

  static const char* value(const ::msgs_demo::SetMap&) { return value(); }
};

template<>
struct DataType< ::msgs_demo::SetMap > {
  static const char* value()
  {
    return "msgs_demo/SetMap";
  }

  static const char* value(const ::msgs_demo::SetMap&) { return value(); }
};


// service_traits::MD5Sum< ::msgs_demo::SetMapRequest> should match 
// service_traits::MD5Sum< ::msgs_demo::SetMap > 
template<>
struct MD5Sum< ::msgs_demo::SetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::SetMap >::value();
  }
  static const char* value(const ::msgs_demo::SetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::SetMapRequest> should match 
// service_traits::DataType< ::msgs_demo::SetMap > 
template<>
struct DataType< ::msgs_demo::SetMapRequest>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::SetMap >::value();
  }
  static const char* value(const ::msgs_demo::SetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msgs_demo::SetMapResponse> should match 
// service_traits::MD5Sum< ::msgs_demo::SetMap > 
template<>
struct MD5Sum< ::msgs_demo::SetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::SetMap >::value();
  }
  static const char* value(const ::msgs_demo::SetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::SetMapResponse> should match 
// service_traits::DataType< ::msgs_demo::SetMap > 
template<>
struct DataType< ::msgs_demo::SetMapResponse>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::SetMap >::value();
  }
  static const char* value(const ::msgs_demo::SetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSGS_DEMO_MESSAGE_SETMAP_H
