// Generated by gencpp from file msgs_demo/TalkerListener.msg
// DO NOT EDIT!


#ifndef MSGS_DEMO_MESSAGE_TALKERLISTENER_H
#define MSGS_DEMO_MESSAGE_TALKERLISTENER_H

#include <ros/service_traits.h>


#include <msgs_demo/TalkerListenerRequest.h>
#include <msgs_demo/TalkerListenerResponse.h>


namespace msgs_demo
{

struct TalkerListener
{

typedef TalkerListenerRequest Request;
typedef TalkerListenerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TalkerListener
} // namespace msgs_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msgs_demo::TalkerListener > {
  static const char* value()
  {
    return "33ea4e5aeb30f5913da681ca459d55f3";
  }

  static const char* value(const ::msgs_demo::TalkerListener&) { return value(); }
};

template<>
struct DataType< ::msgs_demo::TalkerListener > {
  static const char* value()
  {
    return "msgs_demo/TalkerListener";
  }

  static const char* value(const ::msgs_demo::TalkerListener&) { return value(); }
};


// service_traits::MD5Sum< ::msgs_demo::TalkerListenerRequest> should match 
// service_traits::MD5Sum< ::msgs_demo::TalkerListener > 
template<>
struct MD5Sum< ::msgs_demo::TalkerListenerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::TalkerListener >::value();
  }
  static const char* value(const ::msgs_demo::TalkerListenerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::TalkerListenerRequest> should match 
// service_traits::DataType< ::msgs_demo::TalkerListener > 
template<>
struct DataType< ::msgs_demo::TalkerListenerRequest>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::TalkerListener >::value();
  }
  static const char* value(const ::msgs_demo::TalkerListenerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msgs_demo::TalkerListenerResponse> should match 
// service_traits::MD5Sum< ::msgs_demo::TalkerListener > 
template<>
struct MD5Sum< ::msgs_demo::TalkerListenerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::TalkerListener >::value();
  }
  static const char* value(const ::msgs_demo::TalkerListenerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::TalkerListenerResponse> should match 
// service_traits::DataType< ::msgs_demo::TalkerListener > 
template<>
struct DataType< ::msgs_demo::TalkerListenerResponse>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::TalkerListener >::value();
  }
  static const char* value(const ::msgs_demo::TalkerListenerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSGS_DEMO_MESSAGE_TALKERLISTENER_H
