// Generated by gencpp from file msgs_demo/Trigger.msg
// DO NOT EDIT!


#ifndef MSGS_DEMO_MESSAGE_TRIGGER_H
#define MSGS_DEMO_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <msgs_demo/TriggerRequest.h>
#include <msgs_demo/TriggerResponse.h>


namespace msgs_demo
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace msgs_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msgs_demo::Trigger > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::msgs_demo::Trigger&) { return value(); }
};

template<>
struct DataType< ::msgs_demo::Trigger > {
  static const char* value()
  {
    return "msgs_demo/Trigger";
  }

  static const char* value(const ::msgs_demo::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::msgs_demo::TriggerRequest> should match 
// service_traits::MD5Sum< ::msgs_demo::Trigger > 
template<>
struct MD5Sum< ::msgs_demo::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::Trigger >::value();
  }
  static const char* value(const ::msgs_demo::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::TriggerRequest> should match 
// service_traits::DataType< ::msgs_demo::Trigger > 
template<>
struct DataType< ::msgs_demo::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::Trigger >::value();
  }
  static const char* value(const ::msgs_demo::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msgs_demo::TriggerResponse> should match 
// service_traits::MD5Sum< ::msgs_demo::Trigger > 
template<>
struct MD5Sum< ::msgs_demo::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msgs_demo::Trigger >::value();
  }
  static const char* value(const ::msgs_demo::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs_demo::TriggerResponse> should match 
// service_traits::DataType< ::msgs_demo::Trigger > 
template<>
struct DataType< ::msgs_demo::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::msgs_demo::Trigger >::value();
  }
  static const char* value(const ::msgs_demo::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSGS_DEMO_MESSAGE_TRIGGER_H
